#
# docker-compose for local development on stingray.swg.usma.ibm.com
#
# mmccawley@us.ibm.com  2020-09-15
# Use the pattern of docker networking in the .prod.yml versions
# for server/vm deploys.  This is intended for
# local development only on Mike McCawley's MBP with the adjustments
# for working-from-home networking.
#
# Modify this, and two files for deploy on local machines with your
# hostname so that CORS issues with the backend are resolved.
# See https://github.com/doccano/doccano/issues/836
#
version: "3.7"
services:
  backend:
    image: python:3.6
    volumes:
      - .:/src
      - venv:/src/venv
    command: ["/src/app/tools/dev-django.sh", "0.0.0.0:8000"]
    environment:
      HOSTNAME: "stingray.swg.usma.ibm.com"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "notreally" #be nice if I had variable substitution in yaml files.
      ADMIN_EMAIL: "mmccawley@us.ibm.com"
      DATABASE_URL: "postgres://doccano:doccano@postgres:5432/doccano?sslmode=disable"
      ALLOW_SIGNUP: "False"
      DEBUG: "True"
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - network-backend
      - network-frontend

  frontend:
    image: node:13.7.0
    command: ["/src/frontend/dev-nuxt.sh"]
    volumes:
      - .:/src
      - node_modules:/src/frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - network-frontend

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "doccano"
      POSTGRES_PASSWORD: "doccano"
      POSTGRES_DB: "doccano"
    networks:
      - network-backend

volumes:
  postgres_data:
  node_modules:
  venv:

networks:
  network-backend:
  network-frontend:
